### ISSUE TITLE
Request: add cover bonus to target AC

### ISSUE THREAD

**Issue by pcwilcox** [trioderegion/dnd5e-helpers#75] opened 2021-03-10 23:25 UTC
The cover calculation is a really great feature. It would be cool if it could automatically take the next step and apply the AC bonus to attacks the character makes against that target this turn (possibly by automatically adding a condition which imposes a penalty to ranged attacks?).

**Comment by kandashi** [comment] 2021-03-11 10:49
closing as duplicate of #42 
i am slowly looking into this

**Closed by kandashi** 2021-03-11 10:49 UTC
