### ISSUE TITLE
Conflict whit Midi

### ISSUE THREAD

**Issue by rinnocenti** [trioderegion/dnd5e-helpers#131] opened 2021-06-14 02:19 UTC
![image](https://user-images.githubusercontent.com/3178127/121831271-6b79ac80-cc9d-11eb-9baa-dc3e7e09c22a.png)
when there is some programmed action (active macro or effect or MidiQOL.DamageOnlyWorkflow) that deals damage or generates an item attack, the helper tries to fit it as a reaction and causes an error, as no creature is attacking but it is a repeat effect of the DAE.

**Comment by trioderegion** [comment] 2021-06-14 11:00
While I cannot test this explicit setup, I have strengthened the null checks for "odd" chat cards. Please test again with the upcoming 2.0.6 release.

**Comment by trioderegion** [comment] 2021-06-14 13:08
Error still appears per Oskar#7193

**Comment by kandashi** [comment] 2021-08-11 23:55
@rinnocenti can you provide a macro/item to reproduce this error so I can look into this further

**Comment by trioderegion** [comment] 2021-08-29 23:29
Dupe of #143 . Please post any reproduction steps there.

**Closed by trioderegion** 2021-08-29 23:29 UTC
Labels: duplicate
