### ISSUE TITLE
WMS: GM forces spell to surge

### ISSUE THREAD

**Issue by ducky00** [trioderegion/dnd5e-helpers#88] opened 2021-04-17 22:40 UTC
Wild Magic Surge automation could have an option to enable a request to the GM to roll the d100 table instead of rolling it right away automatically, just to give more drama to the thing.

A function to track Favored Enemy feature in an actor's sheet and the types of enemy (could be compatible with the Revised Ranger too), the bonus and damage would be applied automatically.

The upcoming automated cover feature could have an detection for the Sharpshooter feature, making the target not benefit from bonus AC for attacks coming from the actor with the feature.

**Comment by trioderegion** [comment] 2021-04-17 23:39
Some initial thoughts on your 3 suggestions.

1) While I don't think the complexity of prompting the DM to roll on the table is worth the gain from tension, the PHB sorcerer does have the caveat of "at any time, the DM can cause a spell to surge" in the Tides of Chaos feature. With some clever coding and application by the user, we may be able to provide _some_ of this functionality. 
Note: I would not be opposed to it in general if other members of the team have interest in your suggestion as written.

2) Favored Enemy in the PHB has little mechanical automation for which 5e Helpers can assist and I do not intend on supporting UA features (in addition to wanting to leave the Revised Ranger firmly in the past).

3) Detecting Sharpshooter and not applying the attack penalty due to cover is a pretty good suggestion and we'll take that into consideration.

In summation:
1) Low priority, but not outside the scope of 5e Helpers
2) Will not address
3) Good idea, we will tackle this one for sure.

Thank you for your interest and support <3

**Comment by ducky00** [comment] 2021-04-18 14:02
And thank you for taking your time to read my suggestions <3

(Forgot to mention that the Spellsniper feature also ignores cover, same as Sharpshooter: half cover and three quarters cover)

**Comment by trioderegion** [comment] 2021-04-18 14:46
Spellsniper is a good callout, thanks.

**Comment by trioderegion** [comment] 2021-08-12 00:07
Feature (3) was implemented at some point in the 2.x series (lol).

Removing from current milestone and will re-evaluate Feature (1)

**Comment by trioderegion** [comment] 2022-03-09 21:33
Adding this (feature 1) to the 4.1.0 (NEXT) milestone as it is focused on WMS automation.

**Comment by trioderegion** [comment] 2022-03-09 21:34
Actually, closing this ticket as the remaining feature to be implemented is a duplicate of #43

**Closed by trioderegion** 2022-03-09 21:34 UTC
