### ISSUE TITLE
Measured templates disappearing for players 

### ISSUE THREAD

**Issue by Avitale34** [trioderegion/dnd5e-helpers#136] opened 2021-06-15 13:33 UTC
For the last week or so my players canvas goes completely blank when they go to place a measured template, all tokens disappear and they can’t see where they are placing it. No problems on GM side. Turing of 5e helpers stops this issue.

**Comment by trioderegion** [comment] 2021-06-15 14:05
This may be related to #130 and is quite concerning. Any further reproduction details (number of players, template type, template scaling settings) are highly appreciated.

Extremely sorry for these oddities -- they are very surprising...

**Comment by trioderegion** [comment] 2021-06-15 14:18
I may be on to something. I'm not getting the canvas issues, but the templates are disappearing. Going to elevate this and try to push out a fix.

**Comment by Avitale34** [comment] 2021-06-15 14:47
Awesome thank you!

**Comment by trioderegion** [comment] 2021-06-15 15:08
Does this happen with template scaling turned off? There is a dnd5e system bug that might be interfering.

**Comment by Avitale34** [comment] 2021-06-15 15:18
Yes it happens regardless of that feature being on. I did notice the core bug when spinning templates so maybe that has something to do with it.

**Comment by trioderegion** [comment] 2021-06-19 17:51
I am unable to reproduce this error. Can you please check with dnd5e 1.3.5, which contains the ability template preview fix to see if this still occurs. If so, detailed reproduction steps with no other modules enabled would be greatly appreciated. Leaving this issue open for now.

**Comment by trioderegion** [comment] 2021-08-29 23:30
Closing this issue as it continues to be unconfirmed with no additional reports.

**Closed by trioderegion** 2021-08-29 23:30 UTC
Labels: bug, unconfirmed, priority
