### ISSUE TITLE
Feature Request: cover calculation include button to toggle DAE effect

### ISSUE THREAD

**Issue by napolitanod** [trioderegion/dnd5e-helpers#95] opened 2021-05-03 03:55 UTC
The coverage calculation output into the chat is great. Was thinking if this also output a button in that chat window that, when selected, adds a DAE to the target in order to boost the AC for the next attack rolled. Perhaps the script could check that the user has DAE installed before offering that feature. Or, instead of adding DAE, could add a specified CUB condition and that way people can link their own DAE settings to their CUB condition.

Thanks for reading!

**Comment by kandashi** [comment] 2021-05-03 09:10
Duplicate of #75, wil be released in v2.0

**Closed by kandashi** 2021-05-03 09:10 UTC
